App\Entity\User:
  attributes:
    id:
      groups: ['user']
    nombre:
      groups: ['user']
    apellidos:
      groups: ['user']
    poblacion:
      groups: ['user']
    categoria:
      groups: ['user']
    edad:
      groups: ['user']
    activo:
      groups: ['user']
    createdAt:
      groups: ['user']
    clientes:
      groups: ['user']