App\Form\Model\UserDto:
  properties:
    nombre:
      - NotBlank: ~
      - Length:
                min: 3
                max: 250
                minMessage: 'El nombre debe contener al menos {{ limit }} caracteres'
                maxMessage: 'El nombre no puede tener más de {{ limit }} caracteres'
                allowEmptyString: false